### ISSUE TITLE
Tutorial: Signature

### ISSUE THREAD

**Issue by nikiblume** [ZK-Plus/tutorials#13]
- [x] Update content so the signatue generation is done over the znakes package

**Comment by nikiblume** [comment]
@JonathanHeiss @alvaro-alonso first version of the tutorial visible here: https://github.com/ZoKratesPlus/zokratesplus.github.io/blob/test-branch-blog-and-tut-enabled/tutorials/basics/2023-04-01-signature.md

**Comment by alvaro-alonso** [comment]
> @JonathanHeiss @alvaro-alonso first version of the tutorial visible here: https://github.com/ZoKratesPlus/zokratesplus.github.io/blob/test-branch-blog-and-tut-enabled/tutorials/basics/2023-04-01-signature.md

@nikiblume can you please create 2 PR against main, one with the hash tutorial, and another one for the signature?

**Comment by alvaro-alonso** [comment]
@nikiblume I saw you changes :+1: I'll re-assign the ticket to myself now

but at the moment I will move this ticket to the backlog, as I don't have the resources in this sprint to make it.
