### ISSUE TITLE
Add Code to the Hashing Tutorial

### ISSUE THREAD

**Issue by nikiblume** [ZK-Plus/tutorials#15]
Add Code to the Hashing and Signature Tutorial: https://github.com/ZoKratesPlus/tutorials

**Comment by alvaro-alonso** [comment]
@nikiblume Please avoid pushing straight to main. Use PRs.

**Comment by alvaro-alonso** [comment]
@nikiblume 
- the hashing tutorial code was not working as it was. I have make the changes to make it work. This has to be changed in the tutorial site as well. The PR follows.
- Additionally I have removed the signature tutorial as it has not been published. Also the `.py` script does not work as it was.

please review the linked PR

**Comment by alvaro-alonso** [comment]
> [@nikiblume](https://github.com/nikiblume)
> 
>     * the hashing tutorial code was not working as it was. I have make the changes to make it work. This has to be changed in the  website as well. The PR with the fixes of [website](https://github.com/ZK-Plus/ZK-Plus.github.io/pull/66) and [tutorials](https://github.com/ZK-Plus/tutorials/pull/16).
> 
>     * Additionally I have removed the signature tutorial as it has not been published. Also the `.py` script does not work as it is.
> 
> 
> please review the linked PRs and merge if don't find any problem.

@nikiblume what is the status here?? I still see the error in the [tutorial](https://zk-plus.github.io/tutorials/basics/hash/)
